POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIyMzMxNTUsInN1YiI6IjMyZTExMDZlLWRiNmEtNGE2Ny1hYjA3LWJjOTA4ZDdlYzhmMiJ9.dpip0XcDciz5qNsBsEyTEDxTkTWTW6TKjh1WHvwDxcA

{
  "name": "My Product",
  "price": 100
}

###

GET http://localhost:8000/products?page=1&limit=2&sort=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIyMzMxNTUsInN1YiI6IjMyZTExMDZlLWRiNmEtNGE2Ny1hYjA3LWJjOTA4ZDdlYzhmMiJ9.dpip0XcDciz5qNsBsEyTEDxTkTWTW6TKjh1WHvwDxcA

###

GET http://localhost:8000/products/228aac16-1cc5-4eef-8bca-99384bba698c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIyMzMxNTUsInN1YiI6IjMyZTExMDZlLWRiNmEtNGE2Ny1hYjA3LWJjOTA4ZDdlYzhmMiJ9.dpip0XcDciz5qNsBsEyTEDxTkTWTW6TKjh1WHvwDxcA

###

PUT http://localhost:8000/products/228aac16-1cc5-4eef-8bca-99384bba698c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIyMzMxNTUsInN1YiI6IjMyZTExMDZlLWRiNmEtNGE2Ny1hYjA3LWJjOTA4ZDdlYzhmMiJ9.dpip0XcDciz5qNsBsEyTEDxTkTWTW6TKjh1WHvwDxcA

{
  "name": "My Product Updated",
  "price": 300
}

###

DELETE http://localhost:8000/products/228aac16-1cc5-4eef-8bca-99384bba698c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzIyMzMxNTUsInN1YiI6IjMyZTExMDZlLWRiNmEtNGE2Ny1hYjA3LWJjOTA4ZDdlYzhmMiJ9.dpip0XcDciz5qNsBsEyTEDxTkTWTW6TKjh1WHvwDxcA
